version: '3'

services:

  app:
    container_name: app
    build: ./app
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=development
    command: pm2 serve build --no-daemon
  
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app:app
